// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCASDorWXOf1WgDJYnqGcsNHrqd2kFexpg',
    appId: '1:634152380641:web:e5e6f9d5fc308832742fa0',
    messagingSenderId: '634152380641',
    projectId: 'bloodachintha',
    authDomain: 'bloodachintha.firebaseapp.com',
    storageBucket: 'bloodachintha.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4t1MEfJAyhd4mY9MmvQMxuj92qZOshyc',
    appId: '1:634152380641:android:b1365d6e9c7a3d82742fa0',
    messagingSenderId: '634152380641',
    projectId: 'bloodachintha',
    storageBucket: 'bloodachintha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs6fC4bdoDBc5ffi-GAOiH9Pt-lL1jBs8',
    appId: '1:634152380641:ios:5244075225ee2e6c742fa0',
    messagingSenderId: '634152380641',
    projectId: 'bloodachintha',
    storageBucket: 'bloodachintha.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs6fC4bdoDBc5ffi-GAOiH9Pt-lL1jBs8',
    appId: '1:634152380641:ios:5244075225ee2e6c742fa0',
    messagingSenderId: '634152380641',
    projectId: 'bloodachintha',
    storageBucket: 'bloodachintha.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCASDorWXOf1WgDJYnqGcsNHrqd2kFexpg',
    appId: '1:634152380641:web:c56f50016a9aa368742fa0',
    messagingSenderId: '634152380641',
    projectId: 'bloodachintha',
    authDomain: 'bloodachintha.firebaseapp.com',
    storageBucket: 'bloodachintha.appspot.com',
  );

}